-- There are 7 Constraints in DDL (SQL).
-- 1  NOT NULL
-- 2 UNIQUE (combo)
-- 3 PRIMARY KEY
-- 4 AUTO_INCREMENT
-- 5 CHECK
-- 6 DEFAULT
-- 7 FOREIGN KEY


USE vision;

-- 1. NOT NULL use :
CREATE TABLE department(
    d_id INTEGER NOT NULL,
    d_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);


-- 2. UNIQUE use :
CREATE TABLE faculty(
    fid INTEGER NOT NULL UNIQUE,
    f_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

-- 3. PRIMARY KEY use :
CREATE TABLE primary_key(
    pid INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);


-- 4. AUTO_INCREMENT use :
CREATE TABLE auto_increment(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

-- 5. CHECK use :
CREATE TABLE check_(
    cid INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    age NOT NULL CHECK(age > 3 AND age < 25)
);

-- 6. DEFAULT use :
CREATE TABLE default_(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    admission_date NOT NULL DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- 7. FOREIGN KEY use :
CREATE TABLE first_(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE second_(
    pid INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    id INTEGER FOREIGN KEY (pid) REFERENCES first_(id)
);